// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)


String mensagem1;
String mensagem2;
int contadorconsec;
int contadorsaida;
int totalfalhas;

void initProperties(){

  ArduinoCloud.addProperty(mensagem1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(mensagem2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(contadorconsec, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(contadorsaida, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(totalfalhas, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
